name: Build / Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies with Yarn
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: install
      - name: Build package with Yarn
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: build
        env:
          CI: true
