# This is a basic workflow that is manually triggered

name: Bump version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver type of new version (major / minor / patch)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Setup Git
        run: |
          git config user.name 'Gabriel Yamamoto'
          git config user.email 'gabrielyamamoto82@gmail.com'
      - name: Install yarn's version plugin
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: plugin import version
      - name: Bump version
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: version ${{ github.event.inputs.version }} --immediate

      - name: Push latest version
        run: git push origin main --follow-tags
